FROM python:3.11

WORKDIR /app

COPY ./app/predict/requirements.txt .

COPY ./app/utils/db_connection.py .
COPY ./app/utils/app_logger.py .

RUN pip install --no-cache-dir -r ./requirements.txt

COPY ./app/predict .
COPY ./app/utils/db_connection.py ./dataset_creation

CMD ["python3", "-u", "api.py"]