# Use an official Node.js image for development
FROM node:21-alpine AS development

# Install dependencies
WORKDIR /app
COPY ./app/frontend/package*.json ./
COPY ./app/frontend/webpack.config.js ./
RUN npm install 

# Copy source code
COPY ./app/frontend .

EXPOSE 3000

# Start development server
CMD ["npm", "start"]