FROM python:3.11.7-bookworm

WORKDIR /app

COPY ./app/backend/api/requirements.txt .

COPY ./app/utils/db_connection.py .
COPY ./app/utils/app_logger.py .

RUN pip install --no-cache-dir -r ./requirements.txt

COPY ./app/backend/api .

EXPOSE 8080

CMD ["python3", "-u", "api.py"]