FROM python:3.11

WORKDIR /app

COPY ./predict/requirements.txt .

COPY ./utils/db_connection.py .
COPY ./utils/app_logger.py .

RUN pip install --no-cache-dir -r ./requirements.txt

COPY ./predict .

CMD ["python3", "-u", "api.py"]