# Use an official Node.js image for development
FROM node:21-alpine AS development

# Install dependencies
WORKDIR /app
COPY ./frontend/package*.json ./
COPY ./frontend/webpack.config.js ./
RUN npm install 

# Copy source code
COPY ./frontend .

EXPOSE 3000

# Start development server
CMD ["npm", "start"]