FROM python:3.11.7-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y cron curl

COPY ./backend/database/ingestion/requirements.txt .

COPY ./utils/db_connection.py .
COPY ./utils/app_logger.py .

RUN pip install --no-cache-dir -r ./requirements.txt

COPY ./backend/database/ingestion/. .

COPY ./backend/database/ingestion/crontab.txt /etc/cron.d/refresh_data

COPY ./backend/database/ingestion/refresh_scripts/refresh_squad_data.sh .
COPY ./backend/database/ingestion/refresh_scripts/refresh_game_data.sh .
COPY ./backend/database/ingestion/refresh_scripts/refresh_schedule_data.sh .

RUN chmod 0644 /etc/cron.d/refresh_data
RUN chmod +x ./refresh_squad_data.sh
RUN chmod +x ./refresh_schedule_data.sh
RUN chmod +x ./refresh_game_data.sh

RUN crontab /etc/cron.d/refresh_data

EXPOSE 8009

CMD python3 -u __init__.py && cron
