services:
  database:
    container_name: database
    build: ./backend/database/db_setup
    image: pl-postgres
    env_file:
      - ./backend/database/db_setup/.env
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -q -d pl_stats -h database -U postgres || kill 1"
      interval: 5s
      timeout: 5s
      retries: 5

  local-data-ingestion:
    container_name: local-data-ingestion
    build: ./backend/database/ingestion
    image: local-data-ingestion
    env_file:
      - ./backend/database/ingestion/.env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: cat ./ingestion_status.txt
      interval: 30s
      timeout: 3s
      retries: 20
    ports:
      - 8009:8009

  api:
    container_name: api
    build: ./backend/api
    image: api
    env_file:
      - ./backend/api/.env
    depends_on:
      local-data-ingestion:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://api:8080/health"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - 8080:8080
  
  predict:
    container_name: predict
    build: ./predict/
    image: pl-predictor
    env_file:
      - ./predict/.env
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 8008:8008

  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    env_file:
      - ./frontend/.env
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 3000:3000

