name: API to Amazon ECS

on:
  push:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  deploy:
    name: Push API Image to Amazon ECR
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        ref: 'main'
        fetch-depth: 0

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'

    - name: Build, tag, and push Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.API_ECR_REPOSITORY }}
      run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfile.api .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
